name: FlorisBoard CI

on:
  workflow_dispatch:
#  push:
#    branches: [ master ]
#    paths-ignore:
#      - ".github/ISSUE_TEMPLATE/**"
#      - ".github/FUNDING.yml"
#      - ".editorconfig"
#      - "fastlane/**"
#      - "CONTRIBUTING.md"
#      - "CODE_OF_CONDUCT.md"
#      - "LICENSE"
#      - "README.md"
#      - "ROADMAP.md"
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Build with Gradle
        # MUST call gradlew separately because of an OSS license plugin issue.
        # See https://github.com/google/play-services-plugins/issues/199
        run: ./gradlew clean && ./gradlew assemble${{ vars.BUILD_TYPE }}
      - name: Sign & Zip align
        uses: kevin-david/zipalign-sign-android-release@v1.1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/${{ vars.BUILD_TYPE_DOWN }}
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          zipAlign: true
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - uses: actions/upload-artifact@v3
        with:
          name: app.apk
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
